// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

package hello

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloRequest_HelloType int32

const (
	HelloRequest_NOTSET HelloRequest_HelloType = 0
	HelloRequest_HOT    HelloRequest_HelloType = 1
)

var HelloRequest_HelloType_name = map[int32]string{
	0: "NOTSET",
	1: "HOT",
}

var HelloRequest_HelloType_value = map[string]int32{
	"NOTSET": 0,
	"HOT":    1,
}

func (x HelloRequest_HelloType) String() string {
	return proto.EnumName(HelloRequest_HelloType_name, int32(x))
}

func (HelloRequest_HelloType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{0, 0}
}

type HelloRequest struct {
	Subject              string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Type                 HelloRequest_HelloType `protobuf:"varint,2,opt,name=type,proto3,enum=demo.hello.HelloRequest_HelloType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *HelloRequest) GetType() HelloRequest_HelloType {
	if m != nil {
		return m.Type
	}
	return HelloRequest_NOTSET
}

// HelloResponse comment
type HelloResponse struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{1}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterEnum("demo.hello.HelloRequest_HelloType", HelloRequest_HelloType_name, HelloRequest_HelloType_value)
	proto.RegisterType((*HelloRequest)(nil), "demo.hello.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "demo.hello.HelloResponse")
}

func init() { proto.RegisterFile("hello.proto", fileDescriptor_61ef911816e0a8ce) }

var fileDescriptor_61ef911816e0a8ce = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x48, 0xcd, 0xc9,
	0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4a, 0x49, 0xcd, 0xcd, 0xd7, 0x03, 0x8b,
	0x28, 0x35, 0x31, 0x72, 0xf1, 0x78, 0x80, 0x58, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42,
	0x12, 0x5c, 0xec, 0xc5, 0xa5, 0x49, 0x59, 0xa9, 0xc9, 0x25, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c,
	0x41, 0x30, 0xae, 0x90, 0x19, 0x17, 0x4b, 0x49, 0x65, 0x41, 0xaa, 0x04, 0x93, 0x02, 0xa3, 0x06,
	0x9f, 0x91, 0x92, 0x1e, 0xc2, 0x14, 0x3d, 0x64, 0x13, 0x20, 0x9c, 0x90, 0xca, 0x82, 0xd4, 0x20,
	0xb0, 0x7a, 0x25, 0x05, 0x2e, 0x4e, 0xb8, 0x90, 0x10, 0x17, 0x17, 0x9b, 0x9f, 0x7f, 0x48, 0xb0,
	0x6b, 0x88, 0x00, 0x83, 0x10, 0x3b, 0x17, 0xb3, 0x87, 0x7f, 0x88, 0x00, 0xa3, 0x92, 0x32, 0x17,
	0x2f, 0xd4, 0x84, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x21, 0x2e, 0x96, 0x92, 0xd4, 0x0a,
	0x98, 0x0b, 0xc0, 0x6c, 0x23, 0x1f, 0xa8, 0x43, 0x83, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x85,
	0x6c, 0xb8, 0x58, 0xc1, 0x7c, 0x21, 0x09, 0x5c, 0x2e, 0x91, 0x92, 0xc4, 0x22, 0x03, 0xb1, 0xc1,
	0xa8, 0x9b, 0x91, 0x8b, 0x3b, 0x24, 0xb5, 0xb8, 0x04, 0x66, 0x9a, 0x2d, 0x17, 0x1b, 0x58, 0x81,
	0x21, 0x59, 0xc6, 0xc1, 0xb5, 0x1b, 0x91, 0xe7, 0x1a, 0x5e, 0x2e, 0x6e, 0x97, 0xd4, 0x5c, 0x98,
	0xd7, 0x9c, 0xd8, 0xa3, 0x58, 0xc1, 0xaa, 0x92, 0xd8, 0xc0, 0x11, 0x66, 0x0c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0xc8, 0x02, 0xe6, 0x43, 0xbf, 0x01, 0x00, 0x00,
}
